### ISSUE TITLE
Cannot use with Play 2.6.0

### ISSUE THREAD

**Issue by justas79** [gilt/sbt-newrelic#41]
Hello,
I'm getting java.lang.NoSuchMethodError: com.typesafe.sbt.packager.archetypes.JavaAppPackaging$autoImport$.bashScriptExtraDefines()Lsbt/TaskKey;
	at com.gilt.sbt.newrelic.NewRelic$.projectSettings$lzycompute(NewRelic.scala:69)

when trying to use sbt-newrelic with Java Play 2.6.0.
Discussion link: https://groups.google.com/d/topic/play-framework/x4aeVN9R3PI/discussion

**Comment by gmethvin** [comment]
The fix, I think, is to update the sbt-native-packager version to 1.2.0 and create a new release. Looks like a binary incompatible change in sbt-native-packager.

**Comment by fiadliel** [comment]
I had started work on this in master a while ago (before 2.6.0 was released) and got distracted. I'll finish this now.

**Comment by buaya91** [comment]
@fiadliel is there a PR?

**Comment by ehoner** [comment]
@fiadliel I tested this locally and it works with the updated version of `sbt-native-packager % 1.2.0`. The only change was to `build.sbt` removing `-M8`. `scripted` passed all the tests.

**Comment by rodrigogdea** [comment]
Hi, this configuration is not working:
```
addSbtPlugin("com.gilt.sbt" % "sbt-newrelic" % "0.1.15")
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.2")
```

Do you have any workaround?
Thanks!

**Comment by duchoang** [comment]
Same issue with above setting (using scala 2.12), got this exception when loading sbt:
```
java.lang.NoSuchMethodError: com.typesafe.sbt.packager.archetypes.JavaAppPackaging$autoImport$.bashScriptExtraDefines()Lsbt/TaskKey;
	at com.gilt.sbt.newrelic.NewRelic$.projectSettings$lzycompute(NewRelic.scala:91)
	at com.gilt.sbt.newrelic.NewRelic$.projectSettings(NewRelic.scala:50)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$autoPluginSettings$1$1$$anonfun$apply$34.apply(Load.scala:721)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$autoPluginSettings$1$1$$anonfun$apply$34.apply(Load.scala:721)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
```

**Comment by lisinge** [comment]
Having the same issue here with play 2.6 and scala 2.12 and native-packager 1.2.0

**Comment by alexanderscott** [comment]
+1

**Comment by fiadliel** [comment]
v0.2.0 should support Play 2.6:
```scala
addSbtPlugin("com.gilt.sbt" % "sbt-newrelic" % "0.2.0")
```

**Comment by nicodom** [comment]
Thx @fiadliel v0.2.0 worked for me!
